services:
  - type: web
    name: baccarat-premium
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: "10000"
      - key: API_POLL_INTERVAL
        value: "5"
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: TELEGRAM_SESSION
        sync: false
      - key: C1_SILENT_CHANNEL_ID
        sync: false
      - key: PREDICTION_CHANNEL_ID
        sync: false
